### ISSUE TITLE
Uncaught mysqli_sql_exception

### ISSUE THREAD

**Issue by Larsnielsen123** [iceman101184/ajaxcrud#23]
Suddenly this started, i have never had problems

I tried with a new examples page, dosent work

https://jn.stid.dk/crud/examples/example.php

Total Returned Rows: Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /customers/c/0/0/stid.dk/httpd.www/jn/crud/preheader.php:144 Stack trace: #0 /customers/c/0/0/stid.dk/httpd.www/jn/crud/preheader.php(144): mysqli->query('SELECT COUNT(*)...') #1 /customers/c/0/0/stid.dk/httpd.www/jn/crud/ajaxCRUD.class.php(415): q1('SELECT COUNT(*)...') #2 /customers/c/0/0/stid.dk/httpd.www/jn/crud/ajaxCRUD.class.php(773): ajaxCRUD->getNumRows() #3 /customers/c/0/0/stid.dk/httpd.www/jn/crud/examples/example.php(108): ajaxCRUD->insertRowsReturned() #4 {main} thrown in /customers/c/0/0/stid.dk/httpd.www/jn/crud/preheader.php on line 144

**Comment by alloja** [comment]
Hej Lars,
PHP8 seems to break the implementation of the class. In _ajaxCRUD.class.php_, replacing 'class' by '__construct' on line 137 should do the trick.

**Comment by videobuff** [comment]
I have just now the same issue, but replacing 'class' with __construct gives me the following error:

Parse error: syntax error, unexpected identifier "ajaxCRUD" in /var/www/html/kk/ajaxCRUD.class.php on line 133
